# -*- coding: utf-8 -*-
"""Conditional Statement ifelse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHr9ZWKa93rlbspTFvEKuamR-gQgEPhh
"""

Question 1: Write a Python program that checks if a given number is even. If it is, print "Even number".

number = int(input("Enter a number: "))
if number % 2 == 0:
    print("Even number")

"""2: Write a Python program that checks if a given string contains the letter 'a'. If it does, print "String contains 'a'". Question"""

string = input("Enter a string: ")
if 'a' in string:
    print("String contains 'a'")

"""Question 3: Write a Python program that checks if a given year is a leap year. If it is, print "Leap year"."""

year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print("Leap year")

"""Question 4: Write a Python program that checks if a given number is positive. If it is, print "Positive number"""

number = float(input("Enter a number: "))
if number > 0:
    print("Positive number")

"""Question 5: Write a Python program that checks if a given character is a vowel. If it is, print "Vowel"."""

character = input("Enter a character: ")
if character.lower() in 'aeiou':
    print("Vowel")

"""Question 6: Write a Python program that checks if a given number is greater than 100. If it is, print "Greater than 100"."""

number = int(input("Enter a number: "))
if number > 100:
    print("Greater than 100")

string = input("Enter a string: ")
if string == "":
    print("Empty string")

"""Question 8: Write a Python program that checks if a given number is divisible by both 5 and 7. If it is, print "Divisible by 5 and 7"."""

number = int(input("Enter a number: "))
if number % 5 == 0 and number % 7 == 0:
    print("Divisible by 5 and 7")

"""Question 9: Write a Python program that checks if a given list contains any negative numbers. If it does, print "List contains negative numbers"."""

numbers = [int(x) for x in input("Enter numbers separated by space: ").split()]
if any(num < 0 for num in numbers):
    print("List contains negative numbers")

"""Question 10: Write a Python program that checks if a given word is a palindrome. If it is, print "Palindrome"""

word = input("Enter a word: ")
if word == word[::-1]:
    print("Palindrome")

"""Question 1: Write a Python program that checks if a given number is positive. If it is, print "Positive number"; otherwise, print "Negative number"."""

number = float(input("Enter a number: "))
if number > 0:
    print("Positive number")
else:
    print("Negative number")

""". Question 2: Write a Python program that checks if a given string is empty. If it is, print "Empty string"; otherwise, print "Non-empty string"
"""

string = input("Enter a string: ")
if string == "":
    print("Empty string")
else:
    print("Non-empty string")

"""Question 3: Write a Python program that checks if a given number is even. If it is, print "Even number"; otherwise, print "Odd number"
"""

number = int(input("Enter a number: "))
if number % 2 == 0:
    print("Even number")
else:
    print("Odd number")

""". Question 4: Write a Python program that checks if a given character is a vowel. If it is, print "Vowel"; otherwise, print "Consonant"."""

character = input("Enter a character: ")
if character.lower() in 'aeiou':
    print("Vowel")
else:
    print("Consonant")

"""Question 5: Write a Python program that checks if a given year is a leap year. If it is, print "Leap year"; otherwise, print "Not a leap year"."""

year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print("Leap year")
else:
    print("Not a leap year")

"""Question 6: Write a Python program that checks if a given number is divisible by 3. If it is, print "Divisible by 3"; otherwise, print "Not divisible by 3"."""

number = int(input("Enter a number: "))
if number % 3 == 0:
    print("Divisible by 3")
else:
    print("Not divisible by 3")

"""Question 7: Write a Python program that checks if a given string is a palindrome. If it is, print "Palindrome"; otherwise, print "Not a palindrome"."""

word = input("Enter a word: ")
if word == word[::-1]:
    print("Palindrome")
else:
    print("Not a palindrome")

"""Question 8: Write a Python program that checks if a given list is empty. If it is, print "Empty list"; otherwise, print "Non-empty list"
"""

lst = input("Enter elements of the list separated by space: ").split()
if not lst:
    print("Empty list")
else:
    print("Non-empty list")

"""Question 9: Write a Python program that checks if a given number is greater than, less than, or equal to 50. Print the corresponding message"""

number = float(input("Enter a number: "))
if number > 50:
    print("Greater than 50")
elif number < 50:
    print("Less than 50")
else:
    print("Equal to 50")

"""10: Write a Python program that checks if a given character is an uppercase letter. If it is, print "Uppercase"; otherwise, print "Lowercase"."""

character = input("Enter a character: ")
if character.isupper():
    print("Uppercase")
else:
    print("Lowercase")

"""Question 1: Write a Python program that checks if a given number is positive, negative, or zero. Print the corresponding message."""

number = float(input("Enter a number: "))
if number > 0:
    print("Positive")
elif number < 0:
    print("Negative")
else:
    print("Zero")

"""Question 2: Write a Python program that compares two numbers and prints the larger number"""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
if num1 > num2:
    print(f"Larger number: {num1}")
elif num2 > num1:
    print(f"Larger number: {num2}")
else:
    print("Both numbers are equal")

""". Question 3: Write a Python program that determines whether a given temperature is hot, warm, or cold. Print the corresponding message."""

# Get temperature input from the user
temperature_input = input("Enter the temperature in degrees Celsius: ")

# Check if the input is a valid number
if temperature_input.replace('.', '', 1).isdigit() or (temperature_input.startswith('-') and temperature_input[1:].replace('.', '', 1).isdigit()):
    temperature = float(temperature_input)

    # Determine the classification based on the temperature
    if temperature >= 30:
        print("The temperature is classified as: Hot")
    elif 15 <= temperature < 30:
        print("The temperature is classified as: Warm")
    else:
        print("The temperature is classified as: Cold")
else:
    print("Please enter a valid number.")

"""Question 4: Write a Python program that checks if a given year is a leap year, a century year, or neither. Print the corresponding message."""

# Get year input from the user
year_input = input("Enter a year: ")

# Check if the input is a valid number
if year_input.isdigit():
    year = int(year_input)

    # Determine if it is a leap year, century year, or neither
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        print("Leap year")
    elif year % 100 == 0:
        print("Century year")
    else:
        print("Neither a leap year nor a century year")
else:
    print("Please enter a valid year.")

"""Question 5: Write a Python program that categorizes a given character into uppercase letter, lowercase letter, digit, or special character. Print the corresponding message."""

# Get character input from the user
character = input("Enter a character: ")

# Check if the input is a single character
if len(character) == 1:
    # Determine the category of the character
    if character.isupper():
        print("Uppercase letter")
    elif character.islower():
        print("Lowercase letter")
    elif character.isdigit():
        print("Digit")
    else:
        print("Special character")
else:
    print("Please enter a single character.")

"""Question 6: Write a Python program that calculates the discount percentage based on the purchase amount. Print the corresponding discount percentage"""

# Get purchase amount input from the user
purchase_amount_input = input("Enter the purchase amount: ")

# Check if the input is a valid number
if purchase_amount_input.replace('.', '', 1).isdigit() or (purchase_amount_input.startswith('-') and purchase_amount_input[1:].replace('.', '', 1).isdigit()):
    purchase_amount = float(purchase_amount_input)

    # Determine the discount percentage based on the purchase amount
    if purchase_amount >= 1000:
        discount_percentage = 20
    elif purchase_amount >= 500:
        discount_percentage = 10
    elif purchase_amount >= 100:
        discount_percentage = 5
    else:
        discount_percentage = 0

    print(f"The discount percentage is: {discount_percentage}%")
else:
    print("Please enter a valid purchase amount.")

"""Question 7: Write a Python program that checks if a given number is divisible by 2, 3, 5, or none of them. Print the corresponding message."""

# Get number input from the user
number_input = input("Enter a number: ")

# Check if the input is a valid integer
if number_input.isdigit() or (number_input.startswith('-') and number_input[1:].isdigit()):
    number = int(number_input)

    # Check divisibility
    divisible_by = []
    if number % 2 == 0:
        divisible_by.append(2)
    if number % 3 == 0:
        divisible_by.append(3)
    if number % 5 == 0:
        divisible_by.append(5)

    # Print the result
    if divisible_by:
        print(f"The number is divisible by: {', '.join(map(str, divisible_by))}")
    else:
        print("The number is not divisible by 2, 3, or 5.")
else:
    print("Please enter a valid number.")

"""Question 8: Write a Python program that determines the grade based on the percentage obtained. Print the corresponding grade"""

# Get percentage input from the user
percentage_input = input("Enter the percentage obtained: ")

# Check if the input is a valid number
if percentage_input.replace('.', '', 1).isdigit() or (percentage_input.startswith('-') and percentage_input[1:].replace('.', '', 1).isdigit()):
    percentage = float(percentage_input)

    # Determine the grade based on the percentage
    if percentage >= 90:
        grade = 'A'
    elif percentage >= 80:
        grade = 'B'
    elif percentage >= 70:
        grade = 'C'
    elif percentage >= 60:
        grade = 'D'
    elif percentage >= 50:
        grade = 'E'
    else:
        grade = 'F'

    print(f"The grade is: {grade}")
else:
    print("Please enter a valid percentage.")

"""Question 9: Write a Python program that checks if a given number is within a specific range. Print the corresponding message."""

# Get number input from the user
number_input = input("Enter a number: ")

# Check if the input is a valid integer
if number_input.isdigit() or (number_input.startswith('-') and number_input[1:].isdigit()):
    number = int(number_input)

    # Define the range
    lower_bound = 10
    upper_bound = 100

    # Check if the number is within the range
    if lower_bound <= number <= upper_bound:
        print(f"The number {number} is within the range of {lower_bound} and {upper_bound}.")
    else:
        print(f"The number {number} is outside the range of {lower_bound} and {upper_bound}.")
else:
    print("Please enter a valid number.")

"""Question 10: Write a Python program that checks if a given string is an English word, a number, or a combination of both. Print the corresponding message."""

def is_number(s):
    """Check if the string is a number."""
    if s.isdigit():
        return True
    if s.count('.') == 1:  # Check for decimal numbers
        integer_part, dot, decimal_part = s.partition('.')
        return integer_part.isdigit() and decimal_part.isdigit()
    return False

def is_english_word(s):
    """Check if the string is an English word."""
    return s.isalpha()  # Check if all characters are alphabetic

# Get string input from the user
input_string = input("Enter a string: ")

# Check if the input string is a number, an English word, or a combination
if is_number(input_string) and is_english_word(input_string):
    print("The input is a combination of an English word and a number.")
elif is_number(input_string):
    print("The input is a number.")
elif is_english_word(input_string):
    print("The input is an English word.")
else:
    print("The input is neither an English word nor a number.")