# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJL3-4S_i2ovO5-ncEwVkSPAWSH2Cwy7

Question 1: Given a 1D NumPy array arr_1d, extract and print the first element.
arr_1d = np.array([1, 2, 3, 4, 5])
"""

import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[0])  # Output: 1

"""Extract and print the last three elements of a 1D NumPy array"""

import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[-3:])  # Output: [3 4 5]

"""Extract and print the element at the second row and third column of a 2D NumPy array."""

import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])  # Output: 6

"""Extract and print the first row of a 2D NumPy array."""

import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0])  # Output: [1 2 3]

"""Question 5
Extract and print the last column of a 2D NumPy array.
"""

import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[:, -1])  # Output: [3 6 9]

"""Question 6
Extract and print the element at the second matrix, third row, and third column of a 3D NumPy array.
"""

import numpy as np

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d[1, 2, 2])  # Output: 18

"""Question 7
Extract and print the first matrix of a 3D NumPy array.
"""

import numpy as np

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d[0])  # Output: [[1 2 3] [4 5 6] [7 8 9]]

"""Question 8
Extract and print the last matrix of a 3D NumPy array.
"""

import numpy as np

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d[1])  # Output: [[10 11 12] [13 14 15] [16 17 18]]