# -*- coding: utf-8 -*-
"""second_assignment_Python_anudip.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDCdKU1vlJ87I_Ha_uLtD9lXJFkQyapJ

##1. Take two numbers as input from the user and display their difference
"""

num1 = int(input("Write First Number to Calculate the theri Difference = "))
num2 = int(input("Write Second Number to Calculate the theri Difference = "))

difference = num1 - num2

print(f"The difference between the this {num1} and {num2} is = ", difference)

"""##2. Write a Python program to calculate the perimeter of a rectangle using the formula: perimeter = 2 * (length + width).

"""

num1 = int(input("Write Lenght to Calculate the theri Perimeter of a Rectangle = "))
num2 = int(input("Write Width to Calculate the theri Perimeter of a Rectangle = "))

r_perimeter = 2 * (num1 + num2)

print(f"The Perimeter of a Rectangle lenght {num1} and width {num2} is = ", r_perimeter)

"""##3. Take a number as input from the user and display 10 times that number."""

num1 = int(input("Write Number to Calculate 10 times of that number = "))

num_10_times = 10 * num1

print(f"The calculated 10s time of {num1} is = ", num_10_times)

"""##4. Write a Python program to calculate the average of four numbers entered by the user.

"""

num1 = int(input("Write First Number out of Four to Calculate the average of four numbers = "))
num2 = int(input("Write second Number out of Four to Calculate the average of four numbers = "))
num3 = int(input("Write Third Number out of Four to Calculate the average of four numbers = "))
num4 = int(input("Write forth Number out of Four to Calculate the average of four numbers = "))

average_of_4_Number = (num1 + num2 + num3 + num4) / 4

print(f"The average of {num1}, {num2}, {num3}, {num4} is = ", average_of_4_Number)

"""##5. Write a Python program to swap two numbers using a temporary variable.

"""

num1 = int(input("Write First Number out of Two to swap numbers = "))
num2 = int(input("Write second Number out of Two to swap numbers = "))

temp_var = num1
num1 = num2
num2 = temp_var

print(f"The Swaped Number is {num1}, {num2}")

"""##6. Take three numbers as input from the user and display their sum and product.

"""

num1 = int(input("Write First Number out of Three to Calculate the Sum And Product = "))
num2 = int(input("Write second Number out of Three to Calculate the Sum And Product = "))
num3 = int(input("Write Third Number out of Three to Calculate the Sum And Product = "))

sum_of_3_num = (num1 + num2 + num3)
product_of_3_num = (num1 * num2 * num3)

print(f"The Sum of {num1}, {num2} and {num3} is = {sum_of_3_num}\nThe Product of {num1}, {num2} and {num3} is = {product_of_3_num}")

"""##7. Write a Python program to take two numbers as input and display the result of their multiplication.

"""

num1 = int(input("Write First Number to Calculate the Multiplication = "))
num2 = int(input("Write Second Number to Calculate the Multiplication = "))

multiplication = num1 * num2

print(f"The multiplication the this {num1} and {num2} is = {multiplication}")

"""##8. Take two numbers as input and display the result of their subtraction.

"""

num1 = int(input("Write First Number to Calculate the Subtraction = "))
num2 = int(input("Write Second Number to Calculate the Subtraction = "))

subtraction = (num1 - num2)

print(f"The Subtraction the this {num1} and {num2} is = {subtraction}")

"""##9. Write a Python program to find the result of dividing two numbers and display the quotient only.

"""

num1 = int(input("Write First Number to Calculate the Quotient = "))
num2 = int(input("Write Second Number to Calculate the Quotient = "))

quotient = (num1 / num2)

print(f"The Subtraction the this {num1} and {num2} is = {quotient}")

"""##10. Take two numbers as input and display the result of their modulus operation (remainder).

"""

num1 = int(input("Write First Number to Perform the Modulus Operation = "))
num2 = int(input("Write Second Number to Perform the Modulus Operation = "))

modulus_operation = (num1 % num2)

print(f"The Modulus Operation the this {num1} and {num2} is = {modulus_operation}")

"""##11. Write a Python program to calculate the simple interest using the formula: SI = (P * R * T) / 100.

"""

num1 = int(input("Give the Principal to Calculate the Simple Interest = "))
num2 = int(input("Give the Rate of Interest to Calculate the Simple Interest = "))
num3 = int(input("Give the Time(Duration) to Calculate the Simple Interest = "))

simple_interest = (num1 * num2 * num3)/100

print(f"The Simple Interest of Principal {num1}, Rate of Interest {num2} and Time(Duration){num3} is = {simple_interest}")

"""##12. Take the radius as input and calculate the circumference of a circle using the formula: C = 2 * π * r (use 3.14159 for π).

"""

num1 = int(input("Give the Radius to Calculate the Circumference of a Circle = "))

num2 = (2*3.14159*num1)

print(f"The Circumference of a Circle of given Radius{num1} is = {num2}")

"""##13. Write a Python program to calculate the area of a square using the formula: area = side * side."""

num1 = int(input("Give the Side to Calculate the Area of a Square = "))

num2 = (num1*num1)

print(f"The Area of a Square of given Side{num1} is = {num2}")

"""##14. Take two numbers as input and display their exponential result using the power operator ().

"""

num1 = int(input("Enter The Base to Calculate the Exponential = "))
num2 = int(input("Enter The Power to Calculate the Exponential = "))

exponential = (num1**num2)

print(f"The Exponential given base{num1} and power{num2} is = {exponential}")

"""##15. Write a Python program to calculate the area of a circle using the formula: area = π * r^2.

"""

num1 = int(input("Give the Radius to Calculate the Area of a Circle = "))

area_of_Circle = (num1**2)*3.14159

print(f"The Area of a Circle of Given Radius{num1} is = {area_of_Circle}")

"""##16. Take the base and exponent as input and display the result of base raised to the exponent."""

num1 = int(input("Enter The Base to Calculate the Exponential = "))
num2 = int(input("Enter The Power to Calculate the Exponential = "))

result = (num1**num2)

print(f"The Exponential given base{num1} and power{num2} is = {result}")

"""##17. Write a Python program to convert an amount in kilometers to meters (1 km = 1000 meters).

"""

num1 = int(input("Enter The Number to Convert an Amount in Kilometers to Meters = "))

result = (num1*1000)

print(f"The given Km is {num1} and it's Kilometers to Meters is = {result} Meters")

"""##18. Take a number as input and display whether it is an even or odd number using modulus (%)."""

num1 = int(input("Enter The Number to Check it is an Even or Odd = "))

if num1%2==0:
  print(f"The Given Number {num1} is Even")
else:
  print(f"The Given Number {num1} is Odd")

"""##19. Write a Python program to calculate the total price of items where the price per item and number of items are provided by the user."""

num1 = int(input("Enter The Price Per Item to Calculate the Total Price = "))
num2 = int(input("Enter The How many items was byed to Calculate the Total Price = "))

result = (num1*num2)

print(f"The provided Price Per Item is {num1}, Items is {num2} and it's Total Price is = {result}")

"""##20. Take three numbers as input from the user and display the result of multiplying the first number by the sum of the second and third numbers.

"""

num1 = int(input("Enter The First Number = "))
num2 = int(input("Enter The Second Number = "))
num3 = int(input("Enter The Third Number = "))

result = num1 * (num2 + num3)

print(f"The numbers are as follows: First: {num1}, Second: {num2}, and Third: {num3}.\nThe result of multiplying the first number by the sum of the second and third numbers is: {result}")

"""##21. Take the radius as input and calculate the circumference of a circle using the formula: C = 2 * π * r (use 3.14159 for π)."""

num1 = int(input("Give the Radius to Calculate the Circumference of a Circle = "))

num2 = (2*3.14159*num1)

print(f"The Circumference of a Circle of given Radius{num1} is = {num2}")

"""##22. Write a Python program to calculate the area of a square using the formula: area = side * side.

"""

num1 = int(input("Give the Side to Calculate the Area of a Square = "))

num2 = (num1*num1)

print(f"The Area of a Square of given Side{num1} is = {num2}")

"""##23. Take two numbers as input and display their exponential result using the power operator ().

"""

num1 = int(input("Enter The Base to Calculate the Exponential = "))
num2 = int(input("Enter The Power to Calculate the Exponential = "))

exponential = (num1**num2)

print(f"The Exponential given base{num1} and power{num2} is = {exponential}")

"""##24. Write a Python program to calculate the area of a circle using the formula: area = π * r^2.

"""

num1 = int(input("Give the Radius to Calculate the Area of a Circle = "))

area_of_Circle = (num1**2)*3.14159

print(f"The Area of a Circle of Given Radius{num1} is = {area_of_Circle}")

"""##25. Take the base and exponent as input and display the result of base raised to the exponent"""

num1 = int(input("Enter The Base to Calculate the Exponential = "))
num2 = int(input("Enter The Power to Calculate the Exponential = "))

result = (num1**num2)

print(f"The Exponential given base{num1} and power{num2} is = {result}")

"""##26. Write a Python program to convert an amount in kilometers to meters (1 km = 1000 meters)."""

num1 = int(input("Enter The Number to Convert an Amount in Kilometers to Meters = "))

result = (num1*1000)

print(f"The given Km is {num1} and it's Kilometers to Meters is = {result} Meters")

"""##27. Take a number as input and display whether it is an even or odd number using modulus (%).

"""

num1 = int(input("Enter The Number to Check it is an Even or Odd = "))

if num1%2==0:
  print(f"The Given Number {num1} is Even")
else:
  print(f"The Given Number {num1} is Odd")

"""##28. Write a Python program to calculate the total price of items where the price per item and number of items are provided by the user.

"""

num1 = int(input("Enter The Price Per Item to Calculate the Total Price = "))
num2 = int(input("Enter The How many items was byed to Calculate the Total Price = "))

result = (num1*num2)

print(f"The provided Price Per Item is {num1}, Items is {num2} and it's Total Price is = {result}")

"""##29. Take three numbers as input from the user and display the result of multiplying the first number by the sum of the second and third numbers.

"""

num1 = int(input("Enter The First Number = "))
num2 = int(input("Enter The Second Number = "))
num3 = int(input("Enter The Third Number = "))

result = num1 * (num2 + num3)

print(f"The numbers are as follows: First: {num1}, Second: {num2}, and Third: {num3}.\nThe result of multiplying the first number by the sum of the second and third numbers is: {result}")

"""##30. Write a Python program to calculate the speed using the formula: speed = distance / time."""

num1 = int(input("Enter The Distance To Calculate the Speed = "))
num2 = int(input("Enter The Time To Calculate the Speed = "))

result =(num1 / num2)

print(f"The Provide Speed is : {num1} And Time is: {num2}.\n The Calculated Speed is: {result}")